export const samplePrograms = [
  {
    school: "浙江传媒学院",
    program: "数字媒体艺术",
    city: "杭州",
    province: "浙江",
    artCategory: "美术与设计",
    batch: "艺术类一段",
    minScore: 520,
    minRank: 3500,
    planCount: 28,
    tuition: 10300,
    tags: ["城市机会", "低关注高适配"]
  },
  {
    school: "浙江理工大学",
    program: "视觉传达设计",
    city: "杭州",
    province: "浙江",
    artCategory: "美术与设计",
    batch: "艺术类一段",
    minScore: 548,
    minRank: 2100,
    planCount: 18,
    tuition: 10350,
    tags: ["专业强", "城市机会"]
  },
  {
    school: "南京艺术学院",
    program: "环境设计",
    city: "南京",
    province: "江苏",
    artCategory: "美术与设计",
    batch: "艺术类一段",
    minScore: 572,
    minRank: 1500,
    planCount: 16,
    tuition: 11000,
    tags: ["省外机会", "专业强"]
  },
  {
    school: "中国美术学院",
    program: "视觉传达设计",
    city: "杭州",
    province: "浙江",
    artCategory: "美术与设计",
    batch: "艺术类一段",
    minScore: 610,
    minRank: 760,
    planCount: 12,
    tuition: 15000,
    tags: ["目标院校", "顶尖专业"]
  },
  {
    school: "温州肯恩大学",
    program: "视觉传达设计(中外合作)",
    city: "温州",
    province: "浙江",
    artCategory: "美术与设计",
    batch: "艺术类一段",
    minScore: 530,
    minRank: 3000,
    planCount: 20,
    tuition: 68000,
    isSinoForeign: true,
    tags: ["中外合作", "学费换机会"]
  },
  {
    school: "浙江音乐学院",
    program: "书法学",
    city: "杭州",
    province: "浙江",
    artCategory: "书法",
    batch: "艺术类一段",
    minScore: 515,
    minRank: 2600,
    planCount: 22,
    tuition: 10350,
    tags: ["省内强校", "专业强"]
  },
  {
    school: "上海音乐学院",
    program: "书法学",
    city: "上海",
    province: "上海",
    artCategory: "书法",
    batch: "艺术类一段",
    minScore: 595,
    minRank: 900,
    planCount: 8,
    tuition: 10000,
    tags: ["城市机会", "冲刺名校"]
  },
  {
    school: "南京传媒学院",
    program: "播音与主持艺术",
    city: "南京",
    province: "江苏",
    artCategory: "播音",
    batch: "艺术类一段",
    minScore: 540,
    minRank: 2400,
    planCount: 30,
    tuition: 18000,
    tags: ["低关注高适配", "省外机会"]
  },
  {
    school: "浙江工业大学",
    program: "戏剧影视导演",
    city: "杭州",
    province: "浙江",
    artCategory: "表导",
    batch: "艺术类一段",
    minScore: 585,
    minRank: 1400,
    planCount: 15,
    tuition: 10350,
    tags: ["综合大学", "城市机会"]
  },
  {
    school: "北京舞蹈学院",
    program: "舞蹈表演",
    city: "北京",
    province: "北京",
    artCategory: "舞蹈",
    batch: "艺术类一段",
    minScore: 560,
    minRank: 1100,
    planCount: 10,
    tuition: 15000,
    tags: ["顶尖专业", "冲刺名校"]
  },
  {
    school: "杭州师范大学",
    program: "舞蹈学",
    city: "杭州",
    province: "浙江",
    artCategory: "舞蹈",
    batch: "艺术类一段",
    minScore: 518,
    minRank: 2800,
    planCount: 18,
    tuition: 9000,
    tags: ["师范路径", "省内稳妥"]
  },
  {
    school: "浙江师范大学",
    program: "美术学(师范)",
    city: "金华",
    province: "浙江",
    artCategory: "美术与设计",
    batch: "艺术类一段",
    minScore: 556,
    minRank: 1800,
    planCount: 20,
    tuition: 10350,
    tags: ["师范路径", "就业稳定"]
  }
];
